service: yellowipe-linx

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  timeout: 29
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
            - s3:DeleteObject
            - s3:GetObjectAcl
            - s3:PutObjectAcl
          Resource:
            - !Join
              - ''
              - - !GetAtt YellowipeLinxUploadsBucket.Arn
                - '/*'
        - Effect: Allow
          Action:
            - s3:ListBucket
          Resource:
            - !GetAtt YellowipeLinxUploadsBucket.Arn
  httpApi:
    cors:
      allowedOrigins:
        - http://localhost:3000
        - http://localhost:3001
        - http://localhost:5173
        - https://yellowipe-linx.regularjohn.me
        - https://jp-yellowipe-linx-challenge.netlify.app
        - https://jp-yellowipe-linx-challenge-dev.netlify.app
      allowedHeaders:
        - Content-Type
        - X-Amz-Date
        - Authorization
        - X-Api-Key
        - X-Amz-Security-Token
        - X-Amz-User-Agent
        - Accept
        - Origin
        - Referer
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
        - OPTIONS
      allowCredentials: true
      maxAge: 86400
  environment:
    NODE_ENV: ${self:custom.nodeEnv.${self:provider.stage}}
    JWT_SECRET: ${env:JWT_SECRET}
    JWT_EXPIRATION: ${env:JWT_EXPIRATION, '24h'}
    DATABASE_URL: ${env:DATABASE_URL}
    GOOGLE_GMAIL_EMAIL: ${env:GOOGLE_GMAIL_EMAIL}
    GOOGLE_APP_PASSWORD: ${env:GOOGLE_APP_PASSWORD}
    AWS_S3_BUCKET_NAME: !Ref YellowipeLinxUploadsBucket
    AWS_S3_REGION: ${self:provider.region}

functions:
  app:
    handler: src/handler.handler
    timeout: 29
    events:
      - httpApi:
          path: /
          method: ANY
      - httpApi:
          path: /{proxy+}
          method: ANY

resources:
  Resources:
    YellowipeLinxUploadsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: yellowipe-linx-uploads-${self:provider.stage}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - "*"
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              AllowedOrigins:
                - "*"
              MaxAge: 3000

custom:
  dotenv:
    path: .env.${self:provider.stage}
    basePath: ./
    logging: false
    exclude:
      - AWS_PROFILE
  nodeEnv:
    dev: development
    prod: production
  serverless-offline:
    noPrependStageInUrl: true
    httpPort: 4000